### ISSUE TITLE
Native OFT 

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-bridge#57]
## Overview
Deploy native OFT contract for TLOS and add support for native OFT bridge transfers.

## Acceptance Criteria

1. Chain and token selection is consistent with current token bridge 
2. Bridge transfers execute successfully between all network options
3. Transaction progress indicators & history are consistent with current token bridge
4. Optional extra gas on destination is successfully transferred 

## Tasks
- [x] deploy & configure native OFT contract (testnet)
- [x] deploy & configure destination contract(s) (testnet)
- [x] implement UI interface & route
- [x] implement transfer 
- [x] implement gas on destination
- [x] implement transaction progress & history 
- [x] integrate into main bridge interface
- [x] release on testnet
- [x] update network settings for mainnet PR

## Mainnet Contracts
Telos
- [x] Deploy
- [x] Verify
- [x] Configure

Ethereum
- [x] Deploy
- [x] Verify
- [x] Configure

BNB
- [x] Deploy
- [x] Verify
- [x] Configure

Polygon
- [x] Deploy
- [x] Verify
- [x] Configure

Arbitrum
- [x] Deploy
- [x] Verify
- [x] Configure

Avalanche
- [x] Deploy
- [x] Verify
- [x] Configure
